<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Admission</name>
   <tag></tag>
   <elementGuidId>53f3ad25-c0e9-4d6c-8187-237fba63c5b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-3']/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-3 > span > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Admission&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5a41aba5-0e5f-4fb0-96e3-cd48d8a33289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/page/admission.html</value>
      <webElementGuid>b3c01af9-28f4-4c92-9277-ca0390d186f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admission</value>
      <webElementGuid>926f4feb-6dbf-4ebc-8b5d-e73f07cc04b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-3&quot;)/span[1]/a[1]</value>
      <webElementGuid>a6691cd1-57e4-4fbf-87cd-1244ecf9402f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-3']/span/a</value>
      <webElementGuid>cfaa5578-9b56-41bf-b6e5-f9610a2f7730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Admission')])[19]</value>
      <webElementGuid>3442b261-8286-44bc-98d6-6cefee2cb686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Milestones'])[2]/following::a[1]</value>
      <webElementGuid>d32b1a5d-8e6e-41ce-ac72-8b520b42bc2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why MVM'])[3]/following::a[2]</value>
      <webElementGuid>482b3843-227f-4c50-991f-6239b350855e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UG Admission'])[3]/preceding::a[1]</value>
      <webElementGuid>358764f4-b943-47f1-8a00-49949c18379c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG Admission'])[3]/preceding::a[2]</value>
      <webElementGuid>0a101455-61af-49d7-bae6-4c6e47887fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/page/admission.html')])[2]</value>
      <webElementGuid>8bcbebd6-89c5-4c23-8a6a-a9a39ac25ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/span/a</value>
      <webElementGuid>e7b0670f-cce1-48a0-851c-e34953879f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/page/admission.html' and (text() = 'Admission' or . = 'Admission')]</value>
      <webElementGuid>9ba6f0cb-9bba-4def-b706-600f29393af4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
