<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NIRFAISHE</name>
   <tag></tag>
   <elementGuidId>b0ff6c95-a3a3-4162-a0bf-8550968eda6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-241']/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-241 > span > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;NIRF/AISHE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32aac213-9307-4995-9fc7-15ce843a9a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mvmwgacdgl.ac.in/page/nirfaishe.html</value>
      <webElementGuid>bad3f6f9-8617-4811-a2fb-b8c92d093a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NIRF/AISHE</value>
      <webElementGuid>2eae5637-4109-4f46-b1d2-e22045e2da25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-241&quot;)/span[1]/a[1]</value>
      <webElementGuid>d59e86da-dce1-4381-b404-938dbabeb100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-241']/span/a</value>
      <webElementGuid>88c4f775-c22d-4676-8894-f3f0bc1d927a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'NIRF/AISHE')])[3]</value>
      <webElementGuid>074b31dc-d8bb-4809-b324-80a003e0b2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[3]/following::a[7]</value>
      <webElementGuid>09489e76-8f43-4f49-929c-3278555b7fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback Forms'])[2]/following::a[8]</value>
      <webElementGuid>2d166e93-e441-4a51-a86c-4383ab478019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overall'])[2]/preceding::a[1]</value>
      <webElementGuid>f9202202-324d-4fd6-b93e-58093599f106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='College'])[2]/preceding::a[2]</value>
      <webElementGuid>6674a947-cc0b-48b3-9fb8-530f4d7840ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.mvmwgacdgl.ac.in/page/nirfaishe.html')])[6]</value>
      <webElementGuid>5b9cb9a3-f12b-4ad9-8b0a-365707ef933d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[7]/span/a</value>
      <webElementGuid>62741212-740d-49c2-a175-20db0cb9347d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mvmwgacdgl.ac.in/page/nirfaishe.html' and (text() = 'NIRF/AISHE' or . = 'NIRF/AISHE')]</value>
      <webElementGuid>64be6d0b-f17f-428b-8b77-4c1870a41aec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
