<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_RUSA</name>
   <tag></tag>
   <elementGuidId>dc09d041-7d86-4af6-bf72-9425b9054adc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-242']/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-242 > span > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#menu-item-242 >> internal:role=link[name=&quot;RUSA&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>27da5b83-1d51-4950-a0fd-dce741194574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/page/rusa.html</value>
      <webElementGuid>0d2d9775-e73e-4d53-bb58-0c0cc8366da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RUSA</value>
      <webElementGuid>216457c0-fd76-4167-91f0-a863f0726927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-242&quot;)/span[1]/a[1]</value>
      <webElementGuid>5ffa4452-a4f7-49d5-87fe-90991259ae63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-242']/span/a</value>
      <webElementGuid>83b61fba-cfd5-4986-84cc-8d2ec2d6093f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'RUSA')])[5]</value>
      <webElementGuid>fa353685-8194-49eb-a117-78421ca2acb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roll of Honor'])[18]/following::a[1]</value>
      <webElementGuid>545aa335-cd94-4704-a0b8-92b6569cc77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rank Position'])[2]/following::a[2]</value>
      <webElementGuid>c1e9576b-d37c-49d7-bd65-3504f7c03a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Objectives'])[6]/preceding::a[1]</value>
      <webElementGuid>8b7852a3-083b-4a5d-a1ac-7e9b24560c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Components'])[2]/preceding::a[2]</value>
      <webElementGuid>4c8286d9-aff0-458d-9cae-70799b5e2825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/page/rusa.html')])[3]</value>
      <webElementGuid>e26cf6df-78a7-4fc4-a3e8-1e7217b7ad46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[8]/span/a</value>
      <webElementGuid>69742351-2950-454f-a0c3-6abde6b4e2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/page/rusa.html' and (text() = 'RUSA' or . = 'RUSA')]</value>
      <webElementGuid>5c34be0e-cba7-412b-8593-1bf90fc02533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
