<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Address_pe-7s-mail-open-file</name>
   <tag></tag>
   <elementGuidId>137b20c5-f428-4c0d-b7aa-10d5cd96c670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page']/main/div/div/ul/li[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.pe-7s-mail-open-file</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Email address principal@mvmwgacdgl.ac.in&quot;i >> i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f767abb2-665c-43d7-a05c-4dd44406ca30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pe-7s-mail-open-file</value>
      <webElementGuid>5df5c660-000f-4778-843c-0adac8275986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/main[1]/div[@class=&quot;contact_info&quot;]/div[@class=&quot;container&quot;]/ul[@class=&quot;clearfix&quot;]/li[2]/i[@class=&quot;pe-7s-mail-open-file&quot;]</value>
      <webElementGuid>74df0042-6ba9-4a7f-9cba-b4f21f0f5320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/main/div/div/ul/li[2]/i</value>
      <webElementGuid>73b5db54-cefe-494b-9114-d1dd29dc3e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/i</value>
      <webElementGuid>a4c0a27c-8673-4d27-879b-957a54f73537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
