<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Roll of Honor</name>
   <tag></tag>
   <elementGuidId>742fd9ac-da02-4d7b-ba05-7449481f44d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='sidemenu-item-299']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sidemenu-item-299</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sidemenu-item-299</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5aad6f27-ace0-41a8-b941-42e1bac5307e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidemenu-item-299</value>
      <webElementGuid>8689757d-b65f-4c87-8c8e-f414360a4a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item </value>
      <webElementGuid>b7eef2d9-84f3-4ac4-9128-0e223cf1fd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>7f7b7d09-b55a-4888-b90d-1d1be339223e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>586ac965-e155-4f33-b9bc-ceb99f750170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Roll of Honor</value>
      <webElementGuid>21c5d4be-b94a-4cae-b1af-b3f88a8434a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip187568</value>
      <webElementGuid>07a21dc8-d309-4b23-a3b1-c779c7d0bdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Roll of Honor</value>
      <webElementGuid>2a411f65-77ff-4490-bd8e-620df8bad1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidemenu-item-299&quot;)</value>
      <webElementGuid>c4893e3c-2b8f-4b65-8977-a4587ba5c804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='sidemenu-item-299']</value>
      <webElementGuid>8f7e7d81-e76b-4ea8-ab7d-fffb583c9026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sidemenu-itemlink-241']/li[6]</value>
      <webElementGuid>8131b6ac-a067-4f9d-905f-135aca24a69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rank Position'])[2]/following::li[1]</value>
      <webElementGuid>ba926b3d-c780-4ede-84dd-3d5e15238165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UBA Activities'])[2]/following::li[2]</value>
      <webElementGuid>f0595b69-13d2-4c49-8918-69fb3ce7542b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIRF/AISHE'])[7]/preceding::li[1]</value>
      <webElementGuid>a9faeef9-a8d0-4d40-8ecb-3498de3ec777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/ul/li[6]</value>
      <webElementGuid>fc6d7410-6560-49d1-bdd5-22d262a6b44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'sidemenu-item-299' and (text() = ' Roll of Honor' or . = ' Roll of Honor')]</value>
      <webElementGuid>efcddb2e-52bf-47c7-a736-1f50032db86c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
