<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ENQUIRY</name>
   <tag></tag>
   <elementGuidId>0e364604-7631-4c9a-bd42-452a88e0a093</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-6']/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-6 > span > a.hidden-md.hidden-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ENQUIRY&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04b4518a-5ab1-48aa-8a27-19194b746405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://mvmwgacdgl.ac.in/contact.html</value>
      <webElementGuid>f5387945-a407-4798-ab18-591e827de5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hidden-md hidden-lg</value>
      <webElementGuid>3d54f652-38f3-4c3a-a7dd-5d0464e578d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ENQUIRY</value>
      <webElementGuid>7349cc58-090e-4c02-a93d-08a1908b1632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-6&quot;)/span[1]/a[@class=&quot;hidden-md hidden-lg&quot;]</value>
      <webElementGuid>62e40f13-ee39-4ad0-8087-b591ed0c1f9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-6']/span/a</value>
      <webElementGuid>396b7d4d-b5f4-4915-828e-22af99d0a30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'ENQUIRY')])[2]</value>
      <webElementGuid>d95e0e30-4bfa-4986-bb06-78d0d3aa692e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library Gallery'])[2]/following::a[1]</value>
      <webElementGuid>35dbb5bb-4fb1-421e-9cda-393f7b2d0dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Library Blog'])[4]/following::a[2]</value>
      <webElementGuid>876fff76-3c6c-44a7-9c2f-696afca0148d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://mvmwgacdgl.ac.in/contact.html'])[3]</value>
      <webElementGuid>5c438a13-e8e3-4b0e-a582-f20c7330ebf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[12]/span/a</value>
      <webElementGuid>549e9ee0-3dd7-46cd-a89e-46123379ea16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://mvmwgacdgl.ac.in/contact.html' and (text() = 'ENQUIRY' or . = 'ENQUIRY')]</value>
      <webElementGuid>cf088861-d09b-4c2f-b4ac-112e432ef4b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
