<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_College office</name>
   <tag></tag>
   <elementGuidId>b9760acd-e2c9-4ae0-9336-a3120bf20da9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-255']/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-255 > span > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;College office&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a40f60fa-6f29-4f86-8b48-f04895838cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/page/college-office.html</value>
      <webElementGuid>4b7e9dd2-6eab-4ac5-96d3-c6c51f61b91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>College office</value>
      <webElementGuid>964aa74c-373c-4c0b-9870-4ca4260dc1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-255&quot;)/span[1]/a[1]</value>
      <webElementGuid>0e5f6026-c381-41a8-b76b-92bddf98ad9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-255']/span/a</value>
      <webElementGuid>82069a52-0144-4501-afc1-788514ce8c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'College office')])[2]</value>
      <webElementGuid>6c65d435-08d5-4144-817f-424685c794d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Website Committee'])[2]/following::a[1]</value>
      <webElementGuid>3c11ae82-12e2-4118-bda1-d65157d21019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student Activity Committees'])[2]/following::a[2]</value>
      <webElementGuid>5399514d-eb73-4f8d-8e45-1d33d3955c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hostel'])[2]/preceding::a[1]</value>
      <webElementGuid>d122be56-a556-4498-99a1-d5509cd2b44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sports'])[2]/preceding::a[2]</value>
      <webElementGuid>52911494-4671-43d2-b603-99092406c76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/page/college-office.html')])[2]</value>
      <webElementGuid>a0b935f4-1b96-4b76-bea9-a42afcd1cc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/ul/li[2]/span/a</value>
      <webElementGuid>c9354ee4-5bdf-47f1-8679-ff54d34cfbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/page/college-office.html' and (text() = 'College office' or . = 'College office')]</value>
      <webElementGuid>2595d8b3-e42e-4982-b5db-c801a3bfb0d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
