<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NAD</name>
   <tag></tag>
   <elementGuidId>7d3dce47-6faf-4ca0-a9b6-6b48d28ab1e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-811']/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-item-811 > span > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;NAD&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e6a0f52f-40d9-43c2-9f86-9de9a1dea790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/page/nad.html</value>
      <webElementGuid>a3cee33b-37ce-4333-acaa-cfc420fbf7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NAD</value>
      <webElementGuid>5c991ff9-30a2-4fb6-bdd0-faa11bdb994b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-811&quot;)/span[1]/a[1]</value>
      <webElementGuid>7e283b4c-9c94-4d9b-90f4-98c17545bb86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-811']/span/a</value>
      <webElementGuid>a3149b40-bb32-4264-b847-bf819bda34c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'NAD')])[8]</value>
      <webElementGuid>242695c7-0e43-4ebb-a338-015b2ca78c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UGC'])[3]/following::a[1]</value>
      <webElementGuid>d6c0ae34-d479-4d86-89b6-9cc4bcf43945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SWAYAM'])[6]/following::a[2]</value>
      <webElementGuid>cfdffc92-4fab-409a-9b77-80118e999d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NAD Home'])[2]/preceding::a[1]</value>
      <webElementGuid>682bec6b-f5ce-4ed2-acec-086450371578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Committee'])[3]/preceding::a[3]</value>
      <webElementGuid>26784eed-14b8-4cc8-9360-05779e343dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/page/nad.html')])[3]</value>
      <webElementGuid>f25044d0-b755-4744-9bd7-9cc6bf376f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[9]/span/a</value>
      <webElementGuid>6d4b32be-74ed-4f80-94f6-36fe5b15ccf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/page/nad.html' and (text() = 'NAD' or . = 'NAD')]</value>
      <webElementGuid>c48fd21c-7629-4ae2-9689-53b3cb77c967</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
